import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import captainDashboardRoutes from "../modules/captain-dashboard/captain-dashboard.routes.js";
import earningsRoutes from "../modules/earnings/earnings.routes.js";
import notificationRoutes from "../modules/notifications/notifications.routes.js";
import officeRoutes from "../modules/office/office.routes.js";
import offersRoutes from "../modules/offers/offers.routes.js";
import profileRoutes from "../modules/profile/profile.routes.js";
import ratingsRoutes from "../modules/reviews/ratings.routes.js";
import reviewsRoutes from "../modules/reviews/reviews.routes.js";
import shipmentRoutes from "../modules/shipments/shipments.routes.js";
import supportRoutes from "../modules/support/support.routes.js";
import trackingRoutes from "../modules/tracking/tracking.routes.js";
import userRoutes from "../modules/users/users.routes.js";
import verificationRoutes from "../modules/verification/verification.routes.js";
import walletRoutes from "../modules/wallet/wallet.routes.js";
import driversRoutes from "../modules/drivers/drivers.routes.js";
import escrowRoutes from "../modules/escrow/escrow.routes.js";
import revenueRoutes from "../modules/revenue/revenue.routes.js";
import adminUsersRoutes from "../modules/admin/users/admin.users.routes.js";
import settingsRoutes from "../modules/admin/setting/settings.routes.js";
import adminOfficesRoutes from "../modules/admin/offices/admin.offices.routes.js";
import adminDashboardRoutes from "../modules/admin/dashboard/admin.dashboard.routes.js";
import adminDisputesRoutes from "../modules/admin/disputes/disputes.routes.js";
import adminRelationshipsRoutes from "../modules/admin/relationships/admin.relationships.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/captain-dashboard", captainDashboardRoutes);
router.use(earningsRoutes);
router.use("/notifications", notificationRoutes);
router.use("/office", officeRoutes);
router.use("/offers", offersRoutes);
router.use("/profile", profileRoutes);
router.use(ratingsRoutes);
router.use("/reviews", reviewsRoutes);
router.use("/shipments", shipmentRoutes);
router.use("/support", supportRoutes);
router.use("/tracking", trackingRoutes);
router.use("/users", userRoutes);
router.use(verificationRoutes);
router.use("/wallet", walletRoutes);
router.use("/drivers", driversRoutes);
router.use("/escrow", escrowRoutes);
router.use("/revenue", revenueRoutes);
router.use("/admin/users", adminUsersRoutes);
router.use("/admin/settings", settingsRoutes);
router.use("/admin/offices", adminOfficesRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
router.use("/admin/disputes", adminDisputesRoutes);
router.use("/admin/relationships", adminRelationshipsRoutes);

export default router;
