export const ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  PENDING_DELETION: "PENDING_DELETION",
  DELETED: "DELETED",
  SUSPENDED: "SUSPENDED",
  // Captain onboarding lifecycle
  PENDING_OTP: "PENDING_OTP",
  PENDING_PASSWORD: "PENDING_PASSWORD",
  PENDING_DOCUMENTS: "PENDING_DOCUMENTS",
  PENDING_ADMIN_REVIEW: "PENDING_ADMIN_REVIEW",
  REJECTED: "REJECTED",
};
